name: Github Pages
on:
  push:
    branches: [ "main" ]
jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Build with pnpm
        run: |
          pnpm install
          pnpm run pages
      - name: Archive artifact
        run: |
          tar \
            --dereference --hard-dereference \
            --directory pages \
            -cvf ${{ runner.temp }}/artifact.tar \
            --exclude=.git \
            --exclude=.github \
            .
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.0.8
        with:
          artifact_name: github-pages
